# This file provides instructions for packaging.

`Sub-NonRole`
	perl_version_from m`Sub::NonRole`;
	version_from      m`Sub::NonRole`;
	readme_from       m`Sub::NonRole`;
	requires          p`Hook::AfterRuntime 0`;
	requires          p`MooX::CaptainHook 0.004`;
	requires          p`Sub::Identify 0`;
	requires          p`Sub::Talisman 0`;
	test_requires     p`Moo 1.000000`;
	test_requires     p`Moo::Role 0`;
	test_requires     p`Test::Requires 0`;
	.

